--DATABASE PROJECT ON LAWYER APPOINTMENT MANAGEMENT SYSTEM 
--BY MD. NASIM HRIDOY (ROLL: 1907104)


-- DELETING THE TABLES IF THEY EXIST

DROP TABLE APPOINTMENT;
DROP TABLE CHAMBER;
DROP TABLE LAWYER;
DROP TABLE CLIENT;



-- CREATION OF LAWYER TABLE
CREATE TABLE LAWYER(
    LAWYER_ID            INTEGER NOT NULL,
    NAME                 VARCHAR(30),
    COURT                VARCHAR(30),
    EMAIL                VARCHAR(50),
    PHONE                VARCHAR(20),
    CATEG                VARCHAR(20),
    FEE                  NUMBER(7)
);

-- MAKING THE PRIMARY KEY OUTSIDE TABLE CREATION 
ALTER TABLE LAWYER ADD CONSTRAINT LAWYER_PK PRIMARY KEY(LAWYER_ID);

-- CHANGING THE NAME OF THE EXISTED COLUMN BY USING ALTER
ALTER TABLE LAWYER RENAME COLUMN CATEG TO CATEGORY;



--CREATION OF CHAMBER TABLE
CREATE TABLE CHAMBER(
    CHAMBER_ID           NUMBER(5) NOT NULL,
    AREA                 VARCHAR(20),
    STREET               VARCHAR(30),
    LAWYER_ID            NUMBER(5) NOT NULL,
    PRIMARY KEY (CHAMBER_ID),
    FOREIGN KEY (LAWYER_ID) REFERENCES LAWYER(LAWYER_ID)
);



--CREATION OF CLIENT TABLE
CREATE TABLE CLIENT(
    CLIENT_ID            NUMBER(5) NOT NULL,
    NAME                 VARCHAR(30) NOT NULL,
    PHONE                VARCHAR(20),
    AGE                  NUMBER(3),
    CONSTRAINT CLIENT_PK PRIMARY KEY (CLIENT_ID)
);

--Modification using alter
ALTER TABLE CLIENT MODIFY AGE NUMBER(3) check(AGE>17);

--Dropping and Adding CONSTRAINT into TABLE CLIENT
ALTER TABLE CLIENT DROP CONSTRAINT CLIENT_PK;
ALTER TABLE CLIENT ADD  CONSTRAINT CLIENT_PK PRIMARY KEY(CLIENT_ID);



--CREATION OF APPOINTMENT TABLE
CREATE TABLE APPOINTMENT
(
    APPOINTMENT_ID       INTEGER NOT NULL,
    LAWYER_ID            NUMBER(5) NOT NULL,
    CLIENT_ID            NUMBER(5) NOT NULL,
    APPOINTMENT_DATE     DATE,
    PRIMARY KEY (APPOINTMENT_ID),
    FOREIGN KEY (LAWYER_ID) REFERENCES LAWYER(LAWYER_ID) ON DELETE CASCADE,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID) ON DELETE CASCADE
);


