
--VALUE INSERTION OF LAWYER TABLE

INSERT INTO LAWYER VALUES (100,'MR HABIB','JUDGE COURT','habib@gmail.com','01941233774','DIVORCE',1000);
INSERT INTO LAWYER VALUES (101,'HASAN ALI','HIGH COURT','hasan@gmail.com','01735671123','CRIMINAL',2000);
INSERT INTO LAWYER VALUES (102,'SHIHAB','JUDGE COURT','shihab@gmail.com','01312566773','DIVORCE',1500);
INSERT INTO LAWYER VALUES (103,'MR KAYSAR','SUPREME COURT','kaysar@gmail.com','01956342567','REAL ESTATE',3000);
INSERT INTO LAWYER VALUES (104,'RAM GOPAL','HIGH COURT','gopal@gmail.com','01334789067','CORPORATE',1000);
INSERT INTO LAWYER VALUES (105,'FARHAN SAMJI','JUDGE COURT','farrhan@gmail.com','01745322123','CRIMINAL',2000);
INSERT INTO LAWYER VALUES (106,'SAZID BIN HAYAT','SUPREME COURT','sajid@gmail.com','01980567843','CRIMINAL',5000);
INSERT INTO LAWYER VALUES (107,'MAZHARUL ISLAM','HIGH COURT','habib@gmail.com','01345673289','FAMILY',1200);
INSERT INTO LAWYER VALUES (108,'PAPON BIN LADEN','HIGH COURT','habib@gmail.com','01689034522','LABOUR LAWYER',1000);
INSERT INTO LAWYER VALUES (109,'KOWSHIK','JUDGE COURT','habib@gmail.com','01711234567','CORPORATE',2200);
INSERT INTO LAWYER VALUES (110,'MR JALIL','SUPREME COURT','habib@gmail.com','01941233733','CRIMINAL',1000);
INSERT INTO LAWYER VALUES (111,'MR SHAMSUR','HIGH COURT','habib@gmail.com','01735671135','DIVORCE',2000);




--VALUE INSERTION OF CHAMBER TABLE

INSERT INTO CHAMBER VALUES (1,'DHAKA','MIRPUR 2A',100);
INSERT INTO CHAMBER VALUES (2,'SYLHET','MOULABHIBAZAR HAT',101);
INSERT INTO CHAMBER VALUES (3,'KHULNA','SONADANGA',102);
INSERT INTO CHAMBER VALUES (4,'DHAKA','GULISTHAN',103);
INSERT INTO CHAMBER VALUES (5,'BARISAL','BARISAL SADAR',104);
INSERT INTO CHAMBER VALUES (6,'KHULNA','DUCK BANGLA',105);
INSERT INTO CHAMBER VALUES (7,'KHULNA','SHIBBARI',106);
INSERT INTO CHAMBER VALUES (8,'DHAKA','MIRPUR 2A',107);
INSERT INTO CHAMBER VALUES (9,'DHAKA','MIRPUR 10',108);
INSERT INTO CHAMBER VALUES (10,'CUMILLA','MURADNAGAR',109);




--VALUE INSERTION OF CLIENT TABLE

INSERT INTO CLIENT VALUES (1000,'JALIL','54522',19);
INSERT INTO CLIENT VALUES (1001,'PAPON','564522',30);
INSERT INTO CLIENT VALUES (1002,'KAMRUNNAHAR','64522',35);
INSERT INTO CLIENT VALUES (1003,'RAHEMA BANU','155222',49);
INSERT INTO CLIENT VALUES (1004,'SHAMSUR','26622',61);
INSERT INTO CLIENT VALUES (1005,'UDAY','26667',45);
INSERT INTO CLIENT VALUES (1006,'RIFAT','345677',38);
INSERT INTO CLIENT VALUES (1007,'SAIMON','165934',22);
INSERT INTO CLIENT VALUES (1008,'SHIHAB','165939',32);
INSERT INTO CLIENT VALUES (1009,'KOWSHIK','165965',42);

--WILL SHOW ERROR BECAUSE OF TRIGGER
INSERT INTO CLIENT VALUES (1009,'hridoy','125965',15);




--VALUE INSERTION OF APPOINTMNET TABLE

INSERT INTO APPOINTMENT VALUES (11,100,1000,'22-AUG-2022');
INSERT INTO APPOINTMENT VALUES (12,100,1001,'22-AUG-2022');
INSERT INTO APPOINTMENT VALUES (13,103,1002,'23-AUG-2022');
INSERT INTO APPOINTMENT VALUES (14,104,1003,'23-AUG-2022');
INSERT INTO APPOINTMENT VALUES (15,105,1004,'23-AUG-2022');
INSERT INTO APPOINTMENT VALUES (16,105,1005,'26-AUG-2022');
INSERT INTO APPOINTMENT VALUES (17,106,1006,'27-AUG-2022');
INSERT INTO APPOINTMENT VALUES (18,107,1007,'27-AUG-2022');
INSERT INTO APPOINTMENT VALUES (19,108,1008,'27-AUG-2022');
INSERT INTO APPOINTMENT VALUES (20,109,1009,'27-AUG-2022');


DROP TRIGGER AgeChecking;



--SELECT OPERATION OF THE TABLES
--update lawyer set email='habib@gmail.com' where LAWYER_ID='100';
SET PAGESIZE 400
SET LINESIZE 400
SELECT * FROM LAWYER;
SELECT * FROM CHAMBER;
SELECT * FROM CLIENT;
SELECT * FROM APPOINTMENT;





--Different types of operation

SELECT DISTINCT(CATEGORY) AS DISTINCT_CATEGORY FROM LAWYER;

SELECT COURT AS COURT_NAME FROM LAWYER WHERE NAME LIKE '%HA%';

SELECT * FROM LAWYER WHERE NAME LIKE '_____';

SELECT LAWYER_ID, NAME, CATEGORY FROM LAWYER ORDER BY LAWYER_ID ASC;

SELECT LAWYER_ID, NAME, CATEGORY FROM LAWYER ORDER BY LAWYER_ID DESC;





--The lawyer whose fees is between 2000 and 3000
SELECT LAWYER_ID, NAME FROM LAWYER WHERE FEE BETWEEN 2000 AND 3000;

--The lawyer whose fees is NOT between 2000 and 3000
SELECT LAWYER_ID, NAME FROM LAWYER WHERE FEE NOT BETWEEN 2000 AND 3000;

-- THE LAWYER WHOSE CHAMBER IS LOCATED IN 'DHAKA' BY NESTED QUERY
SELECT LAWYER_ID, NAME FROM LAWYER WHERE LAWYER_ID IN (SELECT LAWYER_ID FROM CHAMBER WHERE AREA = 'DHAKA');

-- THE LAWYER WHOSE CHAMBER IS LOCATED IN 'DHAKA' OR 'KHULNA' BY NESTED QUERY
SELECT LAWYER_ID, NAME FROM LAWYER WHERE LAWYER_ID IN (SELECT LAWYER_ID FROM CHAMBER WHERE AREA = 'DHAKA' OR AREA='KHULNA');


-- FIND THE LAWYER WHO CHARGES HIGHEST FEES BY AGGREGATE FUNCTION
SELECT NAME, FEE FROM LAWYER WHERE FEE IN (SELECT MAX(FEE) FROM LAWYER);

-- FIND THE LAWYER WHO CHARGES LOWEST FEES BY AGGREGATE FUNCTION
SELECT NAME, FEE FROM LAWYER WHERE FEE IN (SELECT MIN(FEE) FROM LAWYER);

-- FIND THE TOTAL NUMBER OF CHAMBERS LOCATED IN DHAKA BY AGGREGATE FUNCTION AND GROUP BY AND HAVING FUNCTION
SELECT COUNT(AREA) AS NUMBER_OF_CHAMBER, AREA FROM CHAMBER GROUP BY AREA HAVING AREA='DHAKA';

-- FIND THE LAWYERS GROUPED BY THEIR TYPE
SELECT COUNT(LAWYER_ID) AS NUMBER_OF_LAWYER, CATEGORY FROM LAWYER GROUP BY CATEGORY;

--All the LAWYER'S and CLIENT'S DETAILS using UNION ALL
SELECT NAME, PHONE FROM LAWYER UNION ALL SELECT NAME, PHONE FROM CLIENT;


--All the LAWYER'S and CLIENT'S DETAILS using UNION

SELECT NAME, PHONE FROM LAWYER UNION SELECT NAME, PHONE FROM CLIENT;

-- LAWYER_ID WHO HAVE APPOINTMENTS BY USING INTERSECT

SELECT LAWYER_ID FROM LAWYER INTERSECT SELECT LAWYER_ID FROM APPOINTMENT;


--All Appointment date of each CLIENT under the LAWYER
SELECT L.NAME AS LAWYER, C.NAME AS CLIENT, A.APPOINTMENT_DATE AS AppDate FROM LAWYER L,CLIENT C,APPOINTMENT A WHERE L.LAWYER_ID=A.LAWYER_ID AND A.CLIENT_ID=C.CLIENT_ID;



-- FIND THE LAWYER WHO ARE LOCATED IN KHULNA WITH LOWEST FEE ASCENDING ORDER BY USING JOIN
SELECT NAME, FEE FROM LAWYER JOIN CHAMBER ON LAWYER.LAWYER_ID = CHAMBER.LAWYER_ID WHERE AREA='KHULNA' ORDER BY FEE ASC;

-- FIND THE LAWYER WHO ARE LOCATED IN DHAKA WITH HIGHEST FEE DESCENDING ORDER BY USING NATURAL JOIN
SELECT NAME, FEE FROM LAWYER NATURAL JOIN CHAMBER WHERE AREA='DHAKA' ORDER BY FEE DESC;

--LAWYER CHAMBER DESCRIPTION by INNER JOIN same as JOIN
SELECT L.NAME, L.CATEGORY, C.AREA, C.STREET FROM LAWYER L INNER JOIN CHAMBER C ON L.LAWYER_ID=C.LAWYER_ID;

--LAWYER CHAMBER DESCRIPTION by LEFT OUTER JOIN
SELECT L.NAME, L.CATEGORY, C.AREA, C.STREET FROM LAWYER L LEFT OUTER JOIN CHAMBER C ON L.LAWYER_ID=C.LAWYER_ID;

--LAWYER CHAMBER DESCRIPTION by RIGHT OUTER JOIN
SELECT L.NAME, L.CATEGORY, C.AREA, C.STREET FROM LAWYER L RIGHT OUTER JOIN CHAMBER C ON L.LAWYER_ID=C.LAWYER_ID;

--LAWYER CHAMBER DESCRIPTION by FULL OUTER JOIN
SELECT L.NAME, L.CATEGORY, C.AREA, C.STREET FROM LAWYER L FULL OUTER JOIN CHAMBER C ON L.LAWYER_ID=C.LAWYER_ID;


--TRANSACTION MANAGEMENT (ROLLBACK, SAVEPOINT)

SELECT * FROM APPOINTMENT;
DELETE FROM APPOINTMENT;
SELECT * FROM APPOINTMENT;
ROLLBACK;
SELECT * FROM APPOINTMENT;

INSERT INTO APPOINTMENT VALUES(31, 106, 1006, '01-JUL-2022');
SAVEPOINT INSERTION1;
INSERT INTO APPOINTMENT VALUES(32, 104, 1001, '02-JUL-2022');
SAVEPOINT INSERTION2;

SELECT * FROM APPOINTMENT;
ROLLBACK TO INSERTION1;
SELECT * FROM APPOINTMENT;

-- MAKING APPOINTMENT DATE 2 MONTHS LATER

SELECT APPOINTMENT_ID, LAWYER_ID, CLIENT_ID, ADD_MONTHS(APPOINTMENT_DATE,2) AS TWO_MONTHS_EXTENSION FROM APPOINTMENT;

-- VIEW (CREATE, UPDATE, DELETE, DROP)

CREATE VIEW CLIENT_VIEW AS SELECT CLIENT_ID, NAME, PHONE FROM CLIENT;
SELECT * FROM CLIENT_VIEW;

UPDATE CLIENT_VIEW SET NAME = 'ABIR' WHERE CLIENT_ID = 1004;
SELECT * FROM CLIENT_VIEW;

DELETE FROM CLIENT_VIEW WHERE CLIENT_ID = 1007;
SELECT * FROM CLIENT_VIEW;

DROP VIEW CLIENT_VIEW;

SELECT CLIENT_ID, NAME, PHONE FROM CLIENT;
